### ISSUE TITLE
大佬 main文件里按照你的顺序执行的时候 会出现一些变量未定义。比如IN[7]里中的加载词向量里的keys未定义。请问能帮忙解答一下吗？谢谢

### ISSUE THREAD

**Issue by 785985821** [aker218/Baidu-2020-Language-and-Intelligent-Technology-Competition-Relation-Extraction-rank15#2]

**Comment by aker218** [comment]
你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。

**Comment by 785985821** [comment]
> 你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。

谢谢，请问一下就是我按照执行顺序放在python文件里执行也行吧

**Comment by aker218** [comment]
> > 你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。
> 
> 谢谢，请问一下就是我按照执行顺序放在python文件里执行也行吧

嗯可以的

**Comment by 785985821** [comment]
> > > 你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。
> > 
> > 
> > 谢谢，请问一下就是我按照执行顺序放在python文件里执行也行吧
> 
> 嗯可以的

你好，就是你新上传的这个，在读取词向量的时候，在IN[6]里第二句中wv_from_text显示未定义。

**Comment by aker218** [comment]
> > > > 你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。
> > > 
> > > 
> > > 谢谢，请问一下就是我按照执行顺序放在python文件里执行也行吧
> > 
> > 
> > 嗯可以的
> 
> 你好，就是你新上传的这个，在读取词向量的时候，在IN[6]里第二句中wv_from_text显示未定义。

上次忘记全部拷贝过来了。。刚刚又更新了，不过运行这个词向量代码需要按照readme给词向量链接下载腾讯词向量并解压到对应文件夹下，请注意提前下载好所需文件。

**Comment by 785985821** [comment]
> > > > > 你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。
> > > > 
> > > > 
> > > > 谢谢，请问一下就是我按照执行顺序放在python文件里执行也行吧
> > > 
> > > 
> > > 嗯可以的
> > 
> > 
> > 你好，就是你新上传的这个，在读取词向量的时候，在IN[6]里第二句中wv_from_text显示未定义。
> 
> 上次忘记全部拷贝过来了。。刚刚又更新了，不过运行这个词向量代码需要按照readme给词向量链接下载腾讯词向量并解压到对应文件夹下，请注意提前下载好所需文件。

好的，谢谢。

**Comment by 785985821** [comment]
> > > > > 你好，是出现错误了，之前从word2vec.ipynb文件将创建词向量相关文件的代码集成到main.ipynb中出了一些问题。刚刚已经更新了main.ipynb，按照新代码运行即可。
> > > > 
> > > > 
> > > > 谢谢，请问一下就是我按照执行顺序放在python文件里执行也行吧
> > > 
> > > 
> > > 嗯可以的
> > 
> > 
> > 你好，就是你新上传的这个，在读取词向量的时候，在IN[6]里第二句中wv_from_text显示未定义。
> 
> 上次忘记全部拷贝过来了。。刚刚又更新了，不过运行这个词向量代码需要按照readme给词向量链接下载腾讯词向量并解压到对应文件夹下，请注意提前下载好所需文件。

大佬，我又来了，就是关系分类数据处理的时候，在in[79]里倒数第四行加载cls_logits变量中cross_results这个文件夹是没有的，请问是不是少了一些东西呀，谢谢解答。
